all:
  facebook:
    app_id:       ~
    app_secret:   ~
    app_url:      ~
    # redirect_url: ~
    
    homepage:     '@homepage'
    app_data:     'from_auth'
    app_scope:    ~
    
    user_data:    [ first_name, last_name ]   # defaults - fb_uid also included
    
    like_gate:
      enabled:            true
      # if want to be able to get past the like gate as a page, have to disable this setting
      enabled_for_admin:  true       
      module:             sfFacebookAppTab
      action:             like
