# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

tab:
  url:   /tab
  param: { module: sfFacebookAppTab, action: tab }
 
canvas:
  url:   /canvas/
  param: { module: sfFacebookAppTab, action: canvas }
  
auth:
  url:   /auth
  param: { module: sfFacebookAppTab, action: auth }
  
auth_scope:
  url:   /auth/:scope
  param: { module: sfFacebookAppTab, action: authAdditional }
  
fb_like:
   url:   /tab/like
   param: { module: sfFacebookAppTab, action: like }
  
redirect:
  url:   /redirect
  param: { module: sfFacebookAppTab, action: redirect }
  
fb_channel:
  url:   /channel
  param: { module: sfFacebookAppTab, action: channel }