# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

tab:
  url:   /tab
  param: { module: sfFacebookAppTab, action: tab }
  
auth:
  url:   /auth
  param: { module: sfFacebookAppTab, action: auth }
  
redirect:
  url:   /redirect
  param: { module: sfFacebookAppTab, action: redirect }